### ISSUE TITLE
Soundcloud Unfollow is incorrectly listing some followers as unfollowers

### ISSUE THREAD

**Issue by bongnostic** [medicor/soundcloud-unfollow#2]
I just discovered that Soundcloud Unfollow is actually listing some followers as non-followers. I only spotted this by chance and now I don't have a clue as to how many actual followers I have stopped following because of this bug. This is very awkward and your website has no contact details. How many other users have fallen victim to this bug? It should be fixed or shut down. I realise this is a "use at your own risk" scenario but I have spent considerable time cultivating my follower list. This is embarrassing for me as my unfollowing actions will be seen by some as a real insult. These are people I would never want to insult and I have no way of even finding who they are to re-follow or apologise to!
Here are two examples I know of:
my soundcloud username is bonggnostic
Two results that should not have been listed are:
Arkestar
Lambmother
and only god knows how many others

**Comment by bongnostic** [comment]
this developer doesn't seem to care

**Comment by 4myle** [comment]
Seems like notifications from my own projects are turned off so I didn't see your issue until yesterday.

First of all - this application is (mainly) for my own, personal use and it runs on my development server. I don't mind if others use it, since it is a public server **but** I take no responsibility whatsoever for any harm it can cause nor do i guarantee any uptime. As you mentioned - use it at you own risk.

Good news is I think I've found the problem. There was a limit imposed on two of the api calls which restricted  them to 500 users each. I saw that you have like 650 followers so the limit was probably the problem. If you are up to it, try again and let me now if it works.

At the same time I also fixed a couple of thing that annoyed me:
- The top header is now smaller so it won't occupy as much screen space (better on mobile units).
- Headers with users name are now clickable and they don't overwrite text below.

**Comment by Poudanet** [comment]
Hello, is there a place where I can use this app?

**Comment by 4myle** [comment]
No, sorry. This is an archived project since Soundcloud changed its api.

**Comment by Poudanet** [comment]
pity... thanks for replying.
